# Generated by Django 6.0.3 on 2026-04-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_experience_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
