# Generated by Django 6.0.3 on 2026-04-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobapplication_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='current_stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('assessment', 'Assessment'), ('followed_up', 'Followed Up'), ('interview', 'Interview Scheduled'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='applied', max_length=50),
        ),
    ]
